#%RAML 0.8
title: Create
version: v0.1.1-20180620
documentation:

  - title: OCF Copyright
    content: Copyright (c) 2018 Open Connectivity Foundation, Inc. All rights reserved.
  - title: OCF License
    content: !include LICENSE.md
  - title: OCF Disclaimer
    content: !include DISCLAIMER.md


schemas:
  - create: !include schemas/oic.if-create-schema.json
  - create-response: !include schemas/oic.if-create-response-schema.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.create"]



/CreateResURI?if=oic.if.create:
    description: |
      Create an item using POST with oic.if.create, URI in the query parameter
      Creates a new resource in the collection and a link pointing to it
    displayName: create

    post:
      description: |
        Create interface example

      queryParameters:
        href:
          type: string

      body:
        application/json:
          schema: create
            example: |
              [
                {
                  "rt": "oic.r.switch.binary",
                  "if": ["oic.if.a", "oic.if.baseline" ],
                  "n":  "Heat Mode",
                  "rep": {
                    "rt": "oic.r.switch.binary",
                    "if": ["oic.if.a", "oic.if.baseline" ],
                    "value": false
                  }
                }
              ]

        responses:
          201:
            body:
              application/json:
                schema: create-response
                  example: |
                    [
                      {
                        "href": "modeswitch",
                        "rt": ["oic.r.switch.binary"],
                        "if": ["oic.if.a", "oic.if.baseline" ],
                        "n":  "Heat Mode",
                        "ins": "39724818",
                        "rep": {
                          "rt": ["oic.r.switch.binary"],
                          "if": ["oic.if.a", "oic.if.baseline" ],
                          "value": false
                        }
                      }
                    ]

    get:
      description: |
        Get observe on create interface

        responses:
          201:
            body:
              application/json:
                schema: create-response
                  example: |
                    [
                      {
                        "href": "modeswitch",
                        "rt": ["oic.r.switch.binary"],
                        "if": ["oic.if.a", "oic.if.baseline" ],
                        "n":  "Heat Mode",
                        "ins": "39724818",
                        "rep": {
                          "rt": ["oic.r.switch.binary"],
                          "if": ["oic.if.a", "oic.if.baseline" ],
                          "value": false
                        }
                      }
                    ]
          204:
